### ISSUE TITLE
make NERDTreeColorMapCustom maps array values of [guifg, ctermfg]

### ISSUE THREAD

**Issue by izelnakri** [tsony-tsonev/nerdtree-git-plugin#1]
many vim setups dont have true colors so it would be nice to support cterm colors  just like PaperColor colorscheme customization: https://github.com/NLKNguyen/papercolor-theme

**Comment by tsony-tsonev** [comment]
Added the changes in 938094860dfe99865f4e4510191061888a1c57d9 , so I'm closing this issue. If it does not work in some way you can reopen it.

**Comment by izelnakri** [comment]
Thank you!
