### ISSUE TITLE
Many spaces

### ISSUE THREAD

**Issue by dyrkow** [tsony-tsonev/nerdtree-git-plugin#3]
Hi, cool fork, thanks :)

But I have this problem and I not understand how to solve it.

![image](https://user-images.githubusercontent.com/8726541/50377542-23c7bc00-0630-11e9-9fc6-34839afd9f73.png)

This is my `.vimrc`

```
...

let g:NERDTreeGitStatusWithFlags = 1
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "⋆",
    \ "Staged"    : "•",
    \ "Untracked" : "∘",
    \ "Dirty"     : "⁖",
    \ "Clean"     : "✔︎",
    \ }

let g:WebDevIconsUnicodeDecorateFolderNodes = 0
let g:NERDTreeGitStatusNodeColorization = 1
let g:NERDTreeColorMapCustom = {
    \ "Modified"  : "#f8cc7a",
    \ "Staged"    : "#7fb777",
    \ "Untracked" : "#e2787b",
    \ "Dirty"     : "#299999",
    \ "Clean"     : "#87939A",
    \ "Ignored"   : "#808080"
    \ }

...
```

**Comment by tsony-tsonev** [comment]
Yep I had that to, it's web devicons related. You can add the following:
```
let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '
let g:WebDevIconsNerdTreeBeforeGlyphPadding = ''
```

**Comment by WebWorkDeveloper** [comment]
@tsony-tsonev Thanks for answer. I'm use
 ```
let g:WebDevIconsNerdTreeAfterGlyphPadding = ''
let g:WebDevIconsNerdTreeBeforeGlyphPadding = ''
```
And in result I have two spaces. But, when I open file and after some time (~5-10seconds) all fine :)

video: https://app.hyfy.io/v/abxM2Olbt3n/

**Comment by tsony-tsonev** [comment]
Try moving the whole configuration and color mappings more to the top and see if the behavior changes.

**Comment by tsony-tsonev** [comment]
@WebWorkDeveloper  what happened, did moving the colors and identation configuration to the top of your vimrc solved your problem. Either way I'll be soon closing this issue, because it does not seem to be a bug with the plugin, it is rather somewhere in your vimrc (because the configs are applied correctly, but after some seconds)

**Comment by WebWorkDeveloper** [comment]
@tsony-tsonev moving the whole configuration and color mapping more to the top don't solve the problem, but you can close this issue)
